SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK B
JOIN BOOK_SALES BS ON B.BOOK_ID = BS.BOOK_ID
WHERE DATE(BS.SALES_DATE) >= '2022-01-01' AND DATE(BS.SALES_DATE) <= '2022-01-31'
GROUP BY CATEGORY
ORDER BY CATEGORY
