-- 코드를 입력하세요
SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, SUM(FP.PRICE * FO.AMOUNT) as TOTAL_SALES
from FOOD_PRODUCT FP join FOOD_ORDER FO on FP.PRODUCT_ID = FO.PRODUCT_ID
where FO.PRODUCE_DATE between "2022-05-01" and "2022-05-31"
group by FP.PRODUCT_NAME
order by TOTAL_SALES desc, FP.PRODUCT_ID asc
