SELECT III.ITEM_ID, II.ITEM_NAME, II.RARITY
FROM ITEM_TREE III
LEFT JOIN ITEM_TREE IT ON III.ITEM_ID = IT.PARENT_ITEM_ID	
JOIN ITEM_INFO II ON II.ITEM_ID = III.ITEM_ID
WHERE IT.ITEM_ID IS NULL
ORDER BY III.ITEM_ID DESC


