SELECT e.EMP_NO, e.EMP_NAME, g.GRADE, e.SAL*g.BONUS_RATE AS BONUS
FROM HR_EMPLOYEES e
JOIN
(SELECT EMP_NO, AVG(SCORE), 
    CASE 
        WHEN AVG(SCORE)>=96 THEN 'S'
        WHEN AVG(SCORE)>=90 THEN 'A'
        WHEN AVG(SCORE)>=80 THEN 'B'
        ELSE 'C'
    END AS GRADE,
    CASE 
        WHEN AVG(SCORE)>=96 THEN 0.2
        WHEN AVG(SCORE)>=90  THEN 0.15
        WHEN AVG(SCORE)>=80 THEN 0.1
        ELSE 0
    END AS BONUS_RATE
FROM HR_GRADE
GROUP BY EMP_NO) AS g 
ON g.EMP_NO=e.EMP_NO
ORDER BY EMP_NO
