SELECT USER_ID, NICKNAME, SUM(BOARD.PRICE) as TOTAL_SALES
FROM USED_GOODS_USER as USER join USED_GOODS_BOARD as BOARD 
on USER.USER_ID = BOARD.WRITER_ID
where BOARD.STATUS = "DONE"
GROUP BY BOARD.WRITER_ID 
having SUM(BOARD.PRICE) >= 700000
order by TOTAL_SALES asc;
