-- 세대 구하기
WITH RECURSIVE A AS (
    SELECT A.ID, A.PARENT_ID, 1 AS GEN
    FROM ECOLI_DATA A
    WHERE PARENT_ID IS NULL
    
    UNION
    
    SELECT E.ID, E.PARENT_ID, A.GEN+1
    FROM ECOLI_DATA E
    JOIN A ON A.ID = E.PARENT_ID -- 이게 종료조건임!!
)

-- 자식 없는거 구하기
SELECT COUNT(*) AS COUNT, A.GEN AS GENERATION
FROM A
LEFT JOIN ECOLI_DATA C ON A.ID = C.PARENT_ID
WHERE C.ID IS NULL
GROUP BY A.GEN
ORDER BY A.GEN


