-- 코드를 입력하세요
SELECT AI.ANIMAL_ID, AI.ANIMAL_TYPE, AI.NAME
FROM ANIMAL_INS AI
JOIN ANIMAL_OUTS AO ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AI.SEX_UPON_INTAKE LIKE 'Intact%' = 1 AND (AO.SEX_UPON_OUTCOME LIKE 'Spayed%' = 1 OR AO.SEX_UPON_OUTCOME LIKE 'Neutered%' = 1)
ORDER BY AI.ANIMAL_ID