WITH SU AS (
    SELECT 
        (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') AS FE,
        (SELECT SUM(CODE) FROM SKILLCODES WHERE NAME = 'Python') AS Py,
        (SELECT SUM(CODE) FROM SKILLCODES WHERE NAME = 'C#') AS C
),
CTE AS (
SELECT 
    CASE
        WHEN SKILL_CODE & s.FE > 0 AND SKILL_CODE & s.Py > 0 THEN 'A'
        WHEN SKILL_CODE & s.C > 0 THEN 'B'
        WHEN SKILL_CODE & s.FE > 0 THEN 'C'
    END AS GRADE, ID, EMAIL    
FROM DEVELOPERS, SU s
)

SELECT *
FROM CTE
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID 


    
    
