SELECT d.DEPT_ID, d.DEPT_NAME_EN, s.AVG_SAL
FROM HR_DEPARTMENT d
JOIN 
(
    SELECT DEPT_ID, ROUND(AVG(SAL),0) AS AVG_SAL
    FROM HR_EMPLOYEES
    GROUP BY DEPT_ID
) AS s
ON s.DEPT_ID = d.DEPT_ID
ORDER BY AVG_SAL DESC
