-- 코드를 입력하세요

SELECT c.CAR_ID,c.CAR_TYPE, ROUND(c.DAILY_FEE*(100-h.DISCOUNT_RATE)/100*30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR c
-- 30일 이상 대여 필터링
JOIN (
    SELECT CAR_TYPE,DURATION_TYPE,DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = '30일 이상'
) AS h ON h.CAR_TYPE = c.CAR_TYPE

WHERE c.CAR_ID NOT IN (
    -- 대여 불가 필터링
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE (
            START_DATE <= '2022-11-30' 
            AND END_DATE >= '2022-11-01'
    )
) 
-- 차종 필터링
AND (c.CAR_TYPE = 'SUV' OR c.CAR_TYPE = '세단') 
-- 금액 필터링
AND (c.DAILY_FEE*(100-h.DISCOUNT_RATE)/100*30 BETWEEN 500000 AND 1999999)
ORDER BY FEE DESC,c.CAR_TYPE ASC, c.CAR_ID DESC
