SELECT UU.USER_ID, UU.NICKNAME, SUM(UB.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD UB
JOIN USED_GOODS_USER UU ON UU.USER_ID = UB.WRITER_ID
WHERE UB.STATUS = 'DONE'
GROUP BY UU.USER_ID, UU.NICKNAME
HAVING SUM(UB.PRICE) >=700000
ORDER BY TOTAL_SALES ASC;
