SELECT t.ID, CASE t.bucket
WHEN 1 THEN 'CRITICAL'
WHEN 2 THEN 'HIGH'
WHEN 3 THEN 'MEDIUM'
ELSE 'LOW'
END AS COLONY_NAME
FROM(SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS bucket
FROM ECOLI_DATA)t
ORDER BY t.ID;

