-- 코드를 작성해주세요
WITH GRADING AS (
    SELECT e.EMP_NO, e.EMP_NAME, e.SAL,
    CASE 
        WHEN AVG(g.SCORE) >= 96 THEN 'S'
        WHEN AVG(g.SCORE) >= 90 THEN 'A'
        WHEN AVG(g.SCORE) >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE
    FROM HR_GRADE g
    JOIN HR_EMPLOYEES e
    ON g.EMP_NO = e.EMP_NO
    GROUP BY g.EMP_NO
)

SELECT EMP_NO, EMP_NAME, GRADE,
CASE
    WHEN GRADE = 'S' THEN SAL*0.2
    WHEN GRADE = 'A' THEN SAL*0.15
    WHEN GRADE = 'B' THEN SAL*0.1
    ELSE 0
END AS BONUS
FROM GRADING
ORDER BY EMP_NO ASC;